### PR TITLE
Build CI dist artifacts without debug assertions

### PR DESCRIPTION
**Pull request by bjorn3**
This significantly improves performance. For example for the simple-raytracer benchmark it goes from a 13% improvement over LLVM to 39% improvement over LLVM.

### CODE REVIEW

**Comment by bjorn3** [comment]
This should fix https://github.com/bjorn3/rustc_codegen_cranelift/issues/1344. Could you please confirm @Elabajaba? You can find the CI artifacts at https://github.com/bjorn3/rustc_codegen_cranelift/actions/runs/4091385626

**Comment by bjorn3** [comment]
I'm going to merge this as it improves compile times a lot. I will leave #1344 open until it is confirmed this fixes the pathological behavior seen on Windows with CI artifacts.

**Comment by Elabajaba** [comment]
> This should fix #1344. Could you please confirm @Elabajaba? You can find the CI artifacts at https://github.com/bjorn3/rustc_codegen_cranelift/actions/runs/4091385626

Sorry I didn't get to this earlier, I had a busy weekend.

Tested it on Windows, and this fixes the `--release` build compile time issue for Naga and wgpu with CI artifacts for me!

**Comment by bjorn3** [comment]
No worries. Thanks for testing!

**Pull request merged**
