### PR TITLE
Support testing of cg_clif in rust's CI

### PR DESCRIPTION
**Pull request by bjorn3**
This will need a change on the rust side too to run `./y.rs prepare --download-dir some/dir` (if not building from a source tarball), vendor all deps as necessary and run `./y.rs test --out-dir some/other/dir --download-dir some/dir`.

r? @jyn514

Part of #1290

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]
Thanks! This broadly looks fine to me - I suspect it might need a couple more changes when you write the test code in bootstrap, but I don't have any concerns :)

**Comment by bjorn3** [comment]
Yeah, I needed a lot more changes. I got a branch over at https://github.com/bjorn3/rust/tree/test_cg_clif_in_ci. I'm going to call it a day for now though. I will sync the changes to this PR tomorrow and after this PR is merged I will first sync all changes to the rust repo before opening a PR with the actual CI integration.

**Comment by jyn514** [comment]
@bjorn3 I've only read the commit descriptions but this looks broadly fine to me still :) let me know if you want a full review.

**Comment by bjorn3** [comment]
There are a couple of things left to implement for me. After that I would appreciate a full review. I will let you know when it is ready.

**Comment by bjorn3** [comment]
Landed part of the changes directly on master: dfaeab8c5c2d53323e30212bbfcde99451d74af5...4ece6d0e4427bc8691e135715867b4bd296a8e7b

**Comment by bjorn3** [comment]
Split out https://github.com/bjorn3/rustc_codegen_cranelift/pull/1374

**Comment by bjorn3** [comment]
Landed 5b3bc29008643203b4de3ffb4c5b5141039c88e6 and 134dc334857e453c50f8ea31b13cbda106204f20 directly on master.

**Comment by bjorn3** [comment]
https://github.com/bjorn3/rustc_codegen_cranelift/pull/1378 made it possible to test entirely with an LLVM compiled standard library. This avoids the need to vendor the standard library dependencies.

**Comment by jyn514** [comment]
i'm not sure when i'll get a chance to look at this, sorry. you could ask someone on bootstrap to review or just open a PR directly to rust-lang/rust.

**Comment by bjorn3** [comment]
I'm going to skip implementing vendoring support on the rust side for now and instead skip the tests that need external crates. I intend to implement it later, but for now even running part of the tests is better than nothing.

@jyn514 no worries. I intend to merge this PR and put up a PR for rust-lang/rust today. Most of the complexity of this PR is vendoring support which isn't relevant for now given the above.

**Pull request merged**
