### PR TITLE
Publish latest build as release

### PR DESCRIPTION
**Pull request by bjorn3**
This is easier to find than artifacts from the CI page and allows downloads without logging in. It also ensures that if I push a broken commit to the master branch people can still find the latest version that passes all tests.

I am still working on making cg_clif distributed with rustup, but until that is done this should be useful for people.

Closes https://github.com/bjorn3/rustc_codegen_cranelift/issues/1337
cc https://github.com/bjorn3/rustc_codegen_cranelift/issues/1349#issuecomment-1478007590

### CODE REVIEW

**Comment by bjorn3** [comment]
For anyone who saw the current release at https://github.com/bjorn3/rustc_codegen_cranelift/releases/tag/dev, this was a test release to test if everything works. By the way did you get a notification every time or only for the first time a release was created under the dev tag?

**Comment by bjorn3** [comment]
cc @frederikhors, @peter-kehl

**Comment by eggyal** [comment]
I received a notification the first time, but not since.

**Comment by frederikhors** [comment]
I was on this unfortunately, so I missed it.

image

I'm glad to help from now. Tell me what do you want to know.

**Comment by frederikhors** [comment]
Now I'm on this instead:

image

**Comment by eggyal** [comment]
FWIW I'm on "all activity".

image

**Comment by bjorn3** [comment]
Maybe to get a notification every time I did have to delete and recreate the release in the release action?

**Comment by frederikhors** [comment]
> Maybe to get a notification every time I did have to delete and recreate the release in the release action?

I do not understand. Can we try right now?

**Comment by bjorn3** [comment]
I can't test it right now as I'm on my phone. I can write the code to delete the release before creating it tomorrow and then trigger a CI run for it.

**Comment by frederikhors** [comment]
Ok. I'm here for you.

**Comment by eggyal** [comment]
Received a release notification.

**Comment by frederikhors** [comment]
> Received a release notification.

Me too.

**Comment by frederikhors** [comment]
image

**Comment by frederikhors** [comment]
Another one now.

**Comment by bjorn3** [comment]
Got a notification for both releases in the github ui too. And it looks like the first notification is entirely gone after the second release, so it won't clobber the notification list if I push multiple times in a row.

**Comment by frederikhors** [comment]
@bjorn3 I just received these two releases notifications emails, is that correct?

- the first:
image

- the second:
image

**Comment by bjorn3** [comment]
Yes, I first merged a PR and a bit later pushed another commit directly to master.

**Pull request merged**
